server:
  port: 8888
spring:
  redis:
    host: localhost # Redis 服务器地址
    port: 6379 # Redis 端口号
    password:  # Redis 密码，如果没有则不需要配置
    database: 0 # Redis 数据库编号
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    username: 2791517764@qq.com
    password:
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yhzx?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:

# 阿里云配置
oss:
  endpoint: oss-cn-chengdu.aliyuncs.com
  keyid:
  keysecret:
  bucketname:




